[server]
headless = true
port = 8501
address = "0.0.0.0"              # accessible depuis le LAN
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#DC2626"         # rouge ICT
backgroundColor = "#0F172A"      # slate 900
secondaryBackgroundColor = "#1E293B"
textColor = "#F1F5F9"
font = "sans serif"
